### ISSUE TITLE
alarm clock problem with own stt server + how to speak?

### ISSUE THREAD

**Issue by royrogermcfreely** [SEPIA-Framework/sepia-docs#104]
hey,

when i use my own stt server and want to set an alarm from the browser, sepia knows what i'm saying but keeps me asking about the time. this doesn't happens when i use the native asr engine from my tablet.

timer works with native and custom stt server. 

is it possible to publish via mqtt something when the timer/alarm is set/finished? cause i have a nice automation from Home Assistant where the light dims, coffee maker start and radio starts.

2.) how can i send text to the tts server with states from home assistant sensors?

**Comment by fquirin** [comment]
Hi @royrogermcfreely ,

I'm afraid this issue with the SEPIA STT server is because numbers are not transformed correctly in every case :-(. This is an issue that exists for a long time now and I've decided to postpone the fix until the new audio library is implemented which will hopefully be in a few weeks.

> 2.) how can i send text to the tts server with states from home assistant sensors?

Do you want SEPIA to speak the results or do you just want to use the TTS server? 
The first case is possible but a bit tricky because it uses the remote-action for audio playback. It will be easier in the next version.
For the second case there is a [REST-like API for TTS](https://github.com/SEPIA-Framework/sepia-docs/blob/dev/API/assist-server.md#text-to-speech)

**Comment by royrogermcfreely** [comment]
ok thanks for the info. the same problem is when i ask the weather and its for example -4° - SEPIA tells me "its minus degree cold" 

kann you give me a example for lets say "good morning roy"? i'm not familiar with that. can i put it in one line to call?

**Comment by fquirin** [comment]
> when i ask the weather and its for example -4° - SEPIA tells me "its minus degree cold"

Oh, which voice was that? The default "robotic" eSpeak voice of the DIY client or maybe some MaryTTS voice?

> kann you give me a example for lets say "good morning roy"?

I'm assuming you want to use the Home Assistant [RESTful Command](https://www.home-assistant.io/integrations/rest_command/) for this?
I have never tried this but here is a wild guess according to Home Assistant docs:
```
rest_command:
  my_request:
    url: http://[assist-server-host]/tts
    method: POST
    content_type: "application/x-www-form-urlencoded"
    payload: "text=Good%20morning%20Roy&lang=en&voice=default&gender=default&mood=5&client=home_assistant&GUUID=USER_ID&PWD=PASSWORD"
```

Make sure to replace `[assist-server-host]` with your SEPIA Server IP and Assistant PORT (e.g. `192.168.178.88:20721` or `localhost:20721` or `my-domain/sepia/assist` etc.) and `USER_ID` with something like `uid1007` and `PASSWORD` with your password in clear text. Instead of GUUID and PWD you can use KEY later (a temporary token instead of clear text password!).

This should give you an answer containing a link to a WAV file. Lets try this first and then see how we can proceed ;-)

**Comment by royrogermcfreely** [comment]
i adapted your code to 
```
  sepia_speak:
    url: http://192.168.0.16:20721/tts
    method: put
    headers:
      content_type: "application/x-www-form-urlencoded"
    payload: "text=Good%20morning%20Roy&lang=en&voice=default&gender=default&mood=5&client=a1&GUUID=uid1007&PWD=SUPERSAVE"
```

Does the client-id in the code has to match the client-id from the device who should speak?
In Home Assistant i get this error: 
```
 Logger: homeassistant.components.rest_command
Source: components/rest_command/__init__.py:136
Integration: RESTful Command (documentation, issues)
First occurred: 7:43:53 PM (1 occurrences)
Last logged: 7:43:53 PM
Error. Url: http://192.168.0.16:20721/tts. Status code 404. Payload: b'text=Good%20morning%20Roy&lang=en&voice=default&gender=default&mood=5&client=a1&GUUID=uid1007&PWD=SUPERSAVE'
```
doesnt say much for me, and the "b" at the payload i dont know whats about

maybe for the last steps i have to ask in the homeassistant community for help 

> Oh, which voice was that? The default "robotic" eSpeak voice of the DIY client or maybe some MaryTTS voice?

dont know anymore since is so hot^^ maybe i will come back to that when it gets colder ;)
