### ISSUE TITLE
Sepia in Docker with openhab integration

### ISSUE THREAD

**Issue by jogi4github** [SEPIA-Framework/sepia-docs#14]
Hello,

I wanted to get an offline voice assistant that's how I got in touch with SEPIA. 
As far as I saw - amazing work and a great framework :-)
My current installation is a docker one, based on your Dockerfile. So far so good. My current problem is that I'm not able to connect to my openhab2 installation. After adding the smarthome_hub_name and smarthome_hub_host address the get devices function does not succeed. If I do the same in a normal installation everything works fine. 
My docker-compose.yml file looks like this and forwards all ports between 20721 - 20726.
```
version: "3"

services:
  sepia:
    container_name: sepia
    image: jogi/sepia:latest
    hostname: sepia
    domainname: local
    ports:
        - 20721:20721
        - 20722:20722
        - 20723:20723
        - 20724:20724
        - 20725:20725
        - 20726:20726
    volumes:
      - './sepia-share/SEPIA:/home/admin/SEPIA'
    restart: always

```
Do I miss something here? Do I have to add a callback address somewhere as the SEPIA source IP will not work due to the docker container setup?

Cheers
Jörg
