### ISSUE TITLE
sepia/home - docker - can not login after installation

### ISSUE THREAD

**Issue by SHU-red** [SEPIA-Framework/sepia-docs#176]
**Describe the bug**
Installed sepia as docker container
Executed bash setup.sh
Set admin and assistant password
Able to open WEB-UIs for

- http://192.mylocalip:20726/sepia/assist/app/index.html
- http://192.mylocalip:20726/sepia/assist/tools/index.html#!home

Logging in does not work because of "Username or Password" wrong

**SEPIA client and server versions**
- SEPIA-Server version: image: Docker: sepia/home:v2.6.1_amd64

**To Reproduce**
1. open http://192.mylocalip:20726/sepia/assist/tools/index.html#!home
2. insert username "admin" and set password (tried many versions by changing it multiple times in bash setup.sh)
3. Message appears "Username or Password wrong"

If i change the server-url at login from
http://192.mylocalip:20726/sepia
to
http://192.mylocalip:20726
it says "Sorry but it seems that the  server does not answer :-(" --> Is this a indication that i do NOT have problems contacting the server (using http://192.mylocalip:20726/sepia) throughout the web-ui?

Also set Insecure origins treated as secure in my vivaldi browser
http://192.mylocalip:20726,http://192.mylocalip:20721

**Expected behavior**
Log-in works and i can interact with sepia

**Additional context**
Homeserver
Running TrueNAS SCALE
Installed Docker --> Running Sepia in Docker

Docker compose:
```
services:
  sepia:
    container_name: sepia
    image: sepia/home:v2.6.1_amd64
    restart: unless-stopped
    ports:
      - "20726:20726"
    volumes:
      - /mnt/tank/docker_volumes/sepia_data:/home/admin/SEPIA
```
