### ISSUE TITLE
Unable to connect via Android app

### ISSUE THREAD

**Issue by taiBsu** [SEPIA-Framework/sepia-docs#200]
**Describe the bug**
I have set up the SEPIA home docker container as a docker-compose container after doing the setup manually via the command given in the installation instruction. My `docker-compose.yml` looks as follows:

```
version: "3"
services:
  sepia:
    image: sepia/home:latest
    container_name: sepia
    restart: always
    volumes:
      - ./home:/home/admin/sepia-home-data
    ports:
      - 20726:20726
      - 20723:20723
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
```

Then after finishing the installation, I set up a reverse proxy to access the sepia backend via sepia.mydomain.com:

```
<IfModule mod_ssl.c>
<VirtualHost *:443>

  ServerName sepia.mydomain.org

  # Define reverse-proxy locations
  ProxyPass / http://sepia:20726/
  ProxyPassReverse / http://sepia:20726/

  # Upgrade WebSocket connection
  <Location /chat/>
    ProxyPass http://sepia:20723/

    RewriteEngine On
    RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
    RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
    RewriteRule /messages/(.*) ws://sepia:20723/messages/$1 [P]
  </Location>

  SSLCertificateFile /etc/letsencrypt/live/net/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/taibsu.net/privkey.pem
  Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

**SEPIA client and server versions**
- Client OS: [e.g. Browser name/iOS with version/Android with version]
- SEPIA-Client version: [e.g. v0.15.2 ... see settings page2 at bottom]
- SEPIA-Server version: [e.g. SEPIA-Home v2.1.3]

**To Reproduce**
2. Click or say '....'
3. See error ...

**Expected behavior**

**Additional context**
